### ISSUE TITLE
Getting error on clip_sample

### ISSUE THREAD

**Issue by metaphorz** [crowsonkb/v-diffusion-jax#2]
Targeting a colab notebook for your code. First tried this colab that begins with:

"https://github.com/crowsonkb/v-diffusion-jax
Original Colab from BoneAmputee, edited by danielrussruss to allow for batch_size > 1, displaying and saving progress.
Update: Fixed a problem blocking ability to change prompt without re-running some additional cells."

and got this error: "RuntimeError: UNKNOWN: Failed to determine best cudnn convolution algorithm: UNKNOWN: GetConvolveAlgorithms failed."

Then, I went to your repository (this one), and just hand-crafted a colab notebook, but then it fails with the same error when I try to run clip_sample.

Any ideas? If you know of a working colab notebook, let me know. Running a v100

**Comment by russelldc** [comment]
This is strange... I just tried running that (in [this Colab](https://colab.research.google.com/drive/1YqXnjwayh_LukZkfhkYbUuHPhGBQzcMQ)) myself, and it is actually the line loading CLIP_JAX that's failing, not the diffusion code.

The CLIP_JAX repo hasn't updated for a while now, so this is making me wondering if some of the basic pre-loaded dependencies/environment on Colab have changed...

**Comment by russelldc** [comment]
Fixed by installing a specific version of jax:
`!pip install jax[cuda11_cudnn805] -f https://storage.googleapis.com/jax-releases/jax_releases.html`

Source:
https://twitter.com/bartman081523/status/1463082222412607490

**Comment by metaphorz** [comment]
I can confirm that the new notebook works on a V100. Had an issue with an A100. I think we can close this unless there is an objection?
